// The curated build records point to full 3.29 guides and their real Path of Building exports.
// Item prices and the league are fetched from poe.ninja's documented economy endpoints.
const BUILDS={
 elementalist:{name:'Ethereal Knives Ignite',creator:'Ronarray',guide:'https://mobalytics.gg/poe/builds/ignite-ethereal-knives-elementalist-build-league-starter-to-endgame',pob:'https://pobb.in/eOtcfO47VWsG',treeBuild:'eOtcfO47VWsG',skill:'Ethereal Knives',tag:'3.29 · LEAGUE STARTER',overview:'League-start Elementalist guide with campaign, early-map, level 90, and endgame variants. Ignite proliferation clears packs; this linked PoB is the current league’s level 86 progression setup.',gems:[['Main link','Ethereal Knives','Combustion','Burning Damage','Cruelty','Swift Affliction'],['Auras / heralds','Malevolence','Herald of Ash','Herald of Ice','Herald of Thunder'],['Utility','Flame Dash','Flammability','Flame Surge']],tree:'This is the real level 86 tree from the current league progression PoB. The linked full guide also has level 90 and endgame trees; use those variants as you progress.',gear:[{slot:'Weapon',name:"Nycta's Lantern",type:'unique',kind:'UniqueWeapon',why:'Actual item in the league progression PoB.'},{slot:'Shield',name:'Bronze Tower Shield',type:'rare',why:'Actual PoB base; rare-item prices depend on modifiers.'},{slot:'Helmet',name:'Zealot Helmet',type:'rare',why:'Actual PoB base; rare-item prices depend on modifiers.'},{slot:'Body',name:'Servant of Decay',type:'unique',kind:'UniqueArmour',why:'Actual item in the league progression PoB.'},{slot:'Amulet',name:'Gloomfang',type:'unique',kind:'UniqueAccessory',why:'Actual item in the league progression PoB.'},{slot:'Ring',name:'Polaric Devastation',type:'unique',kind:'UniqueAccessory',why:'Actual item in the league progression PoB.'},{slot:'Ring',name:'The Taming',type:'unique',kind:'UniqueAccessory',why:'Actual item in the league progression PoB.'},{slot:'Belt',name:'Leather Belt',type:'rare',why:'Actual PoB base; rare-item prices depend on modifiers.'}],sourceLabel:'Ronarray · 3.29 guide + level 86 progression PoB',priceKinds:['UniqueWeapon','UniqueArmour','UniqueAccessory']},
 necromancer:{name:'Poison Summon Raging Spirits',creator:'BalorMage',guide:'https://www.poe-vault.com/guides/balormage-summon-raging-spirits-necromancer-build-guide',pob:'https://pobb.in/7_6IS6EVRZfT',treeBuild:'7_6IS6EVRZfT',skill:'Summon Raging Spirits',tag:'3.29 · STARTER → ENDGAME',overview:'Current 3.29 starter with leveling, non-poison start, poison transition, mid-budget, and min-max variants in Path of Building. Begin with the guide’s low-cost setup and transition only when poison gear fits your budget.',gems:[['Main 6-link','Summon Raging Spirit','Unleash','Unbound Ailments','Void Manipulation','Minion Damage','Multistrike'],['Auras','Discipline','Malevolence','Haste','Determination'],['Utility','Convocation','Desecrate','Despair','Flesh Offering'],['Minion support','Raise Spectre','Minion Life','Meat Shield','Animate Guardian']],tree:'The linked 3.29 PoB contains the guide progression trees and item sets. Select the level-start or budget-appropriate tree; the live allocation preview here uses its active PoB tree.',gear:[{slot:'Weapon',name:'Convoking Wand',type:'rare',why:'Actual PoB base; rare-item prices depend on modifiers.'},{slot:'Shield',name:'Aegis Aurora',type:'unique',kind:'UniqueArmour',why:'Actual item in the 3.29 PoB.'},{slot:'Helmet',name:'Silken Hood',type:'rare',why:'Actual PoB base; rare-item prices depend on modifiers.'},{slot:'Body',name:'The Covenant',type:'unique',kind:'UniqueArmour',why:'Actual item in the 3.29 PoB.'},{slot:'Amulet',name:"Aul's Uprising",type:'unique',kind:'UniqueAccessory',why:'Actual item in the 3.29 PoB.'},{slot:'Belt',name:'Darkness Enthroned',type:'unique',kind:'UniqueAccessory',why:'Actual item in the 3.29 PoB.'},{slot:'Rings',name:'Bone Ring / Unset Ring',type:'rare',why:'Actual PoB bases; rare-item prices depend on modifiers.'}],sourceLabel:'BalorMage · verified 3.29 guide + Path of Building',priceKinds:['UniqueWeapon','UniqueArmour','UniqueAccessory']},
 occultist:{name:'Winter Orb Occultist',creator:'Ronarray',guide:'https://mobalytics.gg/poe/profile/ronarray/builds/3-29-winter-orb-occultist-witch-build-from-league-starter-to-ubers',pob:'https://pobb.in/8cQ3YmPIEgrg',treeBuild:'8cQ3YmPIEgrg',skill:'Winter Orb',tag:'3.29 · STARTER → UBERS',overview:'Updated for the 3.29 Winter Orb buffs. The guide covers league start through Ubers and explicitly provides an all-rare level 90 setup for when the endgame uniques exceed your budget.',gems:[['Main link','Winter Orb','Infused Channelling','Focused Channelling','Power Charge on Critical','Inspiration','Greater Multiple Projectiles'],['Auras','Zealotry','Discipline','Flesh and Stone','Herald of Ice'],['Utility','Frostbite','Elemental Weakness','Arcanist Brand','Frostblink'],['Movement / defense','Shield Charge','Automation','Steelskin','Clarity']],tree:'The linked 3.29 PoB provides progression and endgame trees. Its active tree is shown here; use the all-rare level 90 guide variant when the unique gear is over cap.',gear:[{slot:'Weapon',name:'Tulfall',type:'unique',kind:'UniqueWeapon',why:'Actual item in the linked endgame PoB.'},{slot:'Off-hand',name:"Malachai's Loop",type:'unique',kind:'UniqueArmour',why:'Actual item in the linked endgame PoB.'},{slot:'Helmet',name:'Willclash',type:'unique',kind:'UniqueArmour',why:'Actual item in the linked endgame PoB.'},{slot:'Body',name:'Nightweave Robe',type:'unique',kind:'UniqueArmour',why:'Actual item in the linked endgame PoB.'},{slot:'Boots',name:"Ralakesh's Impatience",type:'unique',kind:'UniqueArmour',why:'Actual item in the linked endgame PoB.'},{slot:'Amulet',name:'Badge of the Brotherhood',type:'unique',kind:'UniqueAccessory',why:'Actual item in the linked endgame PoB.'},{slot:'Rings',name:"Romira's Banquet",type:'unique',kind:'UniqueAccessory',why:'Actual item in the linked endgame PoB.'},{slot:'Belt',name:"Graven's Secret",type:'unique',kind:'UniqueAccessory',why:'Actual item in the linked endgame PoB.'}],sourceLabel:'Ronarray · verified 3.29 guide + Path of Building',priceKinds:['UniqueWeapon','UniqueArmour','UniqueAccessory']}
};
const $=s=>document.querySelector(s);let current='elementalist',market={league:null,divineChaos:null,prices:new Map(),refreshed:null,errors:[]},activeTree=null,treeRequest=0;let toastTimer;
const cap=$('#budget-range');
function notify(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function setBuild(key){current=key;document.querySelectorAll('.asc-nav').forEach(x=>x.classList.toggle('active',x.dataset.class===key));$('#asc-select').value=key;render()}
$('#asc-select').addEventListener('change',e=>setBuild(e.target.value));document.querySelectorAll('.asc-nav').forEach(x=>x.addEventListener('click',()=>setBuild(x.dataset.class)));
$('#budget-range').addEventListener('input',()=>{$('#budget-value').textContent=cap.value;renderGear()});
async function loadMarket(){const btn=$('#refresh-prices');btn.disabled=true;btn.textContent='UPDATING…';$('#market-status').textContent='Connecting to poe.ninja economy data…';try{const response=await fetch('/api/market');if(!response.ok)throw Error('Local market service unavailable. Start the app with node server.js.');const data=await response.json();market.league=data.league;market.divineChaos=data.divineChaos;market.prices=new Map(Object.entries(data.prices||{}));market.refreshed=new Date(data.refreshed);market.errors=data.errors||[];$('#league-name').textContent=data.leagueName||data.league;$('#market-short').textContent=`${(data.leagueName||data.league).toUpperCase()} PRICES`;const currentMatches=/allflame/i.test(data.league||data.leagueName||'');$('#market-status').textContent=`LIVE MARKET · ${data.leagueName||data.league} · updated ${market.refreshed.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}${currentMatches?'':' · these curated build guides are 3.29 references'}${market.errors.length?' · some item categories unavailable':''}`;render()}catch(error){market.errors=[String(error.message||error)];$('#market-status').textContent='Live market unavailable. Start the local app with node server.js; no placeholder prices are shown.';notify('Market data unavailable.');render()}finally{btn.disabled=false;btn.textContent='↻ REFRESH PRICES'}}
function median(arr){const x=arr.slice().sort((a,b)=>a-b);return x[Math.floor(x.length/2)]}
function getPriceRange(item){const values=market.prices.get(item.name);if(!values?.length)return null;return [Math.min(...values),Math.max(...values)]}
function divPrice(chaos){if(chaos==null)return 'Price unavailable';if(market.divineChaos){const d=chaos/market.divineChaos;return `${d<.1?d.toFixed(2):d.toFixed(1)} div`}return `${Math.round(chaos)} chaos`}
function itemQuote(item){const range=getPriceRange(item);if(!range)return 'Price unavailable';const low=divPrice(range[0]),high=divPrice(range[1]);return low===high?high:`${low}–${high} <small>market range</small>`}
function estimate(b,gear=b.gear){let chaosTotal=0,missing=[];gear.forEach(it=>{if(it.type==='unique'){const range=getPriceRange(it);if(range==null)missing.push(it.name);else chaosTotal+=range[1]}});const uniqueDiv=market.divineChaos?chaosTotal/market.divineChaos:null;return{uniqueDiv,missing,rareCount:gear.filter(it=>it.type==='rare').length}}
function drawTree(data){const svg=$('#passive-tree');if(!svg)return;const radii=data.constants?.orbitRadii||[0,82,162,335,493,662,846,1040],perOrbit=data.constants?.skillsPerOrbit||[1,6,16,16,40,72,72];const positions={};for(const [id,n] of Object.entries(data.nodes)){const g=data.groups[n.g];if(!g)continue;const radius=Number(radii[n.o]||0),count=Number(perOrbit[n.o]||1),angle=(2*Math.PI*(Number(n.i)||0)/count);positions[id]=[Number(g.x)+Math.sin(angle)*radius,Number(g.y)-Math.cos(angle)*radius]}
 const ids=Object.keys(positions),allocated=new Set(data.allocated.map(String));if(!ids.length){svg.innerHTML='';return}let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;ids.forEach(id=>{const [x,y]=positions[id];minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)});const pad=Math.max(maxX-minX,maxY-minY)*.035;minX-=pad;minY-=pad;maxX+=pad;maxY+=pad;svg.setAttribute('viewBox',`${minX} ${minY} ${maxX-minX} ${maxY-minY}`);
 let markup='';for(const id of ids){const node=data.nodes[id];for(const to of node.out||[]){const target=String(to);if(id<target&&positions[target]){const [x1,y1]=positions[id],[x2,y2]=positions[target],hot=allocated.has(id)&&allocated.has(target);markup+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="tree-edge${hot?' allocated':''}"/>`}}}
 const size=Math.max(maxX-minX,maxY-minY),r=size*.0026;for(const id of ids){const node=data.nodes[id], [x,y]=positions[id],hot=allocated.has(id),rr=node.k?r*1.7:node.t?r*1.35:node.s?r*1.2:r*.68,cls=`tree-node${hot?' allocated':''}${node.k?' keystone':''}${node.t?' notable':''}${node.s?' jewel':''}`;markup+=`<circle cx="${x}" cy="${y}" r="${rr}" class="${cls}"><title>${(node.name||'Passive node').replace(/[&<>]/g,' ')}</title></circle>`}
 svg.innerHTML=markup;$('#tree-notes').textContent=`${data.specName} · ${allocated.size} allocated passives · official GGG skill-tree data with the real allocation from the linked Path of Building export.`;$('#tree-state').textContent='LIVE TREE DATA'}
async function loadTree(){const serial=++treeRequest,b=BUILDS[current];$('#tree-state').textContent='LOADING OFFICIAL TREE…';try{const res=await fetch(`/api/passives?build=${encodeURIComponent(b.treeBuild)}`);if(!res.ok)throw new Error((await res.json()).error||'Tree service unavailable');const data=await res.json();if(serial!==treeRequest)return;activeTree=data;drawTree(data)}catch(error){if(serial!==treeRequest)return;$('#passive-tree').innerHTML='';$('#tree-notes').textContent=`The official allocation preview could not load. Open the verified PoB export below to see the exact skill tree. ${error.message}`;$('#tree-state').textContent='TREE PREVIEW UNAVAILABLE'}}
function renderGear(){const b=BUILDS[current],capDiv=Number(cap.value),gears=b.gear;let result=estimate(b,gears);const list=$('#gear-list');list.innerHTML=gears.map(it=>{const p=it.type==='unique'?getPriceRange(it):null;const price=it.type==='unique'?itemQuote(it):'Not priced: rare mods vary';return `<div class="gear-row"><div class="item-icon">${it.type==='unique'?'◈':'◇'}</div><div class="item-info"><b>${it.name}</b><span>${it.slot} · ${it.why}</span></div><div class="item-price ${p==null&&it.type==='unique'?'price-missing':''}">${price}</div></div>`}).join('');
 const pricedOver=result.uniqueDiv!=null&&result.uniqueDiv>capDiv;let title,detail;if(result.missing.length){title='Unique-item subtotal is incomplete';detail=`${result.missing.length} unique price${result.missing.length===1?' is':'s are'} missing. Rare gear is not priced. Verify items on the trade site.`}else if(result.uniqueDiv!=null){title=`Up to ${result.uniqueDiv.toFixed(1)} div · listed unique items`;detail=`Uses the high end of live market ranges. ${pricedOver?'These uniques alone exceed':'The listed uniques are below'} your ${capDiv} div cap. ${result.rareCount?'Rare gear is not included; exact costs depend on modifiers.':'No rare gear in this setup.'}`}else{title='Waiting for live market data';detail='No sample prices are shown. Rare items depend on their exact modifiers.'}
 $('#budget-result').innerHTML=`<b>${title}</b><span>${detail}</span>`;$('#budget-result').classList.toggle('over',pricedOver);$('#affordability').textContent=result.missing.length?'PRICE CHECK INCOMPLETE':pricedOver?'UNIQUES OVER CAP':result.uniqueDiv!=null?'UNIQUES UNDER CAP':'PRICE CHECK PENDING';$('#affordability').className=`pill ${pricedOver?'warning':'pill-hot'}`;
 $('#trade-link').href=`https://www.pathofexile.com/trade/search/${encodeURIComponent(market.league||'Standard')}`;
}
function render(){const b=BUILDS[current];$('#crumb-class').textContent=current.toUpperCase();$('#build-name').textContent=b.name;$('#build-subtitle').textContent=b.overview;$('#hero-tag').textContent=b.tag;$('#hero-tag-pill').textContent=b.tag;$('#guide-link').href=b.guide;$('#pob-link').href=b.pob;$('#source-label').textContent=b.sourceLabel;$('#gems-content').innerHTML=b.gems.map(([label,...gems])=>`<div class="gem-group"><span class="gem-label">${label}</span><div class="gem-items">${gems.map((g,i)=>`<span class="gem ${['red','blue','green','aqua'][(i+g.length)%4]}"><i></i>${g}</span>`).join('')}</div></div>`).join('');$('#guide-source').textContent=`Build guide by ${b.creator} · updated for Path of Exile 3.29 Curse of the Allflame`;renderGear();loadTree()}
$('#generate-btn').addEventListener('click',()=>{render();notify(`Showing verified 3.29 ${BUILDS[current].name} build.`)});
$('#refresh-prices').addEventListener('click',loadMarket);
$('#share-btn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(`${BUILDS[current].name} — Path of Exile 3.29 · ${BUILDS[current].guide}`);notify('Build guide link copied.')}catch{notify('Use the guide and PoB links to share this build.')}});
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(btn.dataset.view==='saved')notify('Saved builds are not stored in this prototype.')}));
render();loadMarket();
